---
# ============================================
# Playbook AWX: Cinder Volume Backup (One-Shot)
# Eseguito dallo schedule per fare backup automatici
# ============================================

- name: Create Cinder Volume Backup
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
    # =============================================
    # 1. VALIDAZIONE INPUT
    # =============================================
    
    - name: Validate required variables
      assert:
        that:
          - volume_id is defined and volume_id | length > 0
          - tenant_name is defined and tenant_name | length > 0
          - retention_days is defined
        fail_msg: "ERROR: Missing required variables (volume_id, tenant_name, retention_days)"
        success_msg: "Variables OK - volume_id: {{ volume_id }}, tenant: {{ tenant_name }}"
    
    # =============================================
    # 2. RECUPERA NOME VOLUME DA OPENSTACK (CON FALLBACK)
    # =============================================
    
    - name: Try to get volume from OpenStack
      block:
        - name: Get all volumes from OpenStack
          openstack.cloud.volume_info:
            details: true
          register: all_volumes
        
        - name: Find volume by ID
          set_fact:
            volume_data: "{{ all_volumes.volumes | selectattr('id', 'equalto', volume_id) | first | default(None) }}"
        
        - name: Check if volume exists in OpenStack
          fail:
            msg: "Volume {{ volume_id }} not found in OpenStack"
          when: volume_data is none
        
        - name: Set volume name from OpenStack
          set_fact:
            volume_name: "{{ volume_data.name }}"
        
        - name: Display success - volume found in OpenStack
          debug:
            msg: "✓ Volume trovato in OpenStack: {{ volume_name }}"
      
      rescue:
        - name: Cinder service not available - using fallback
          debug:
            msg: 
              - "⚠ Servizio Cinder non disponibile o non accessibile"
              - "Utilizzo backup_name o volume_id come identificatore"
        
        - name: Set fallback volume name
          set_fact:
            volume_name: "{{ backup_name | default('volume_' ~ volume_id[:8]) }}"
            volume_data:
              id: "{{ volume_id }}"
              name: "{{ backup_name | default('volume_' ~ volume_id[:8]) }}"
        
        - name: Display fallback info
          debug:
            msg: "✓ Utilizzo nome fallback: {{ volume_name }}"
    
    # =============================================
    # 3. GENERA NOME BACKUP FINALE
    # Format: anno_mese_giorno_nome_backup_tenant
    # =============================================
    
    - name: Generate date prefix
      set_fact:
        date_prefix: "{{ ansible_date_time.year }}_{{ '%02d' | format(ansible_date_time.month | int) }}_{{ '%02d' | format(ansible_date_time.day | int) }}"
    
    - name: Clean tenant name
      set_fact:
        clean_tenant_name: "{{ tenant_name | regex_replace('[^a-zA-Z0-9_-]', '_') }}"
    
    - name: Check if custom backup_name is provided
      set_fact:
        has_backup_name: "{{ backup_name is defined and backup_name | length > 0 }}"
    
    - name: Use custom backup name if provided
      set_fact:
        clean_backup_name: "{{ backup_name | regex_replace('[^a-zA-Z0-9_-]', '_') }}"
      when: has_backup_name
    
    - name: Generate default backup name from volume if not provided
      set_fact:
        clean_backup_name: "backup_{{ volume_name | regex_replace('[^a-zA-Z0-9_-]', '_') }}"
      when: not has_backup_name
    
    - name: Compose final backup name (date + name + tenant)
      set_fact:
        final_backup_name: "{{ date_prefix }}_{{ clean_backup_name }}_{{ clean_tenant_name }}"
    
    # =============================================
    # 4. DISPLAY INFO
    # =============================================
    
    - name: Display backup info
      debug:
        msg:
          - "=============================================="
          - "INIZIO BACKUP"
          - "=============================================="
          - "Volume ID: {{ volume_id }}"
          - "Volume Name: {{ volume_name }}"
          - "Tenant: {{ tenant_name }}"
          - "---"
          - "Nome backup finale: {{ final_backup_name }}"
          - "  - Data: {{ date_prefix }}"
          - "  - Nome: {{ clean_backup_name }}"
          - "  - Tenant: {{ clean_tenant_name }}"
          - "---"
          - "Retention: {{ retention_days }} giorni"
          - "=============================================="
    
    # =============================================
    # 5. CREA BACKUP
    # =============================================
    
    - name: Create volume backup
      openstack.cloud.volume_backup:
        volume: "{{ volume_id }}"
        state: present
        force: true
        name: "{{ final_backup_name }}"
        description: "Backup automatico daily - Retention {{ retention_days }}gg - Tenant: {{ tenant_name }}"
      register: backup_result
    
    - name: Wait for backup to complete
      openstack.cloud.volume_backup_info:
        name: "{{ final_backup_name }}"
      register: backup_status
      until: backup_status.volume_backups[0].status in ['available', 'error']
      retries: 60
      delay: 10
      when: backup_result is defined
    
    - name: Check backup status
      fail:
        msg: "Backup failed with status: {{ backup_status.volume_backups[0].status }}"
      when: 
        - backup_status is defined
        - backup_status.volume_backups[0].status == 'error'
    
    # =============================================
    # 6. GESTIONE RETENTION
    # =============================================
    
    - name: Get all backups for this volume
      openstack.cloud.volume_backup_info:
      register: all_backups
    
    - name: Filter backups for this volume only
      set_fact:
        volume_backups: "{{ all_backups.volume_backups | selectattr('volume_id', 'equalto', volume_id) | list }}"
    
    - name: Sort backups by creation date (oldest first)
      set_fact:
        sorted_backups: "{{ volume_backups | sort(attribute='created_at') }}"
    
    - name: Calculate retention date
      set_fact:
        retention_date: "{{ (ansible_date_time.epoch | int - (retention_days | int * 86400)) | int }}"
    
    - name: Filter old backups to delete
      set_fact:
        old_backups: "{{ sorted_backups | selectattr('created_at', 'defined') | 
                        rejectattr('created_at', 'search', '9999') | 
                        list | 
                        map('combine', {'created_epoch': (item.created_at | to_datetime('%Y-%m-%dT%H:%M:%S')).strftime('%s') | int}) | 
                        selectattr('created_epoch', 'lt', retention_date | int) | 
                        list }}"
      vars:
        item: "{{ sorted_backups[0] | default({}) }}"
      when: sorted_backups | length > 0
    
    - name: Delete old backups
      openstack.cloud.volume_backup:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ old_backups | default([]) }}"
      when: 
        - old_backups is defined
        - old_backups | length > 0
      ignore_errors: true
    
    # =============================================
    # 7. SUMMARY
    # =============================================
    
    - name: Show success message
      debug:
        msg:
          - "=============================================="
          - "BACKUP COMPLETATO"
          - "=============================================="
          - "Backup Name: {{ final_backup_name }}"
          - "Backup ID: {{ backup_result.backup.id | default('N/A') }}"
          - "Volume: {{ volume_name }} ({{ volume_id }})"
          - "Tenant: {{ tenant_name }}"
          - "Status: {{ backup_status.volume_backups[0].status | default('unknown') }}"
          - "---"
          - "Backup totali per questo volume: {{ volume_backups | length }}"
          - "Backup eliminati (retention): {{ old_backups | default([]) | length }}"
          - "Retention policy: {{ retention_days }} giorni"
          - "=============================================="
