---
- name: Execute OpenStack Cinder Volume Backup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Debug - Show volume_id received from ManageIQ
      debug:
        msg: "Creating backup for volume: {{ volume_id }}"
    
    - name: Ensure OpenStack volume backup is created
      openstack.cloud.volume_backup:
        volume: "{{ volume_id }}"
        state: present
        force: true
        name: "backup-{{ volume_id }}-{{ '%Y%m%d%H%M' | strftime }}"
      register: backup_result
    
    - name: Show backup result
      debug:
        msg: "Backup created successfully: {{ backup_result.backup.name }}"
