---
- name: Execute OpenStack Cinder Volume Backup
  hosts: localhost
  connection: local
  gather_facts: true  # ← serve per ansible_date_time
  tasks:
    - name: Debug - Show volume_id received from ManageIQ
      debug:
        msg: "Creating backup for volume: {{ volume_id }}"
      tags: debug
    
    - name: Ensure OpenStack volume backup is created
      openstack.cloud.volume_backup:
        volume: "{{ volume_id }}"
        state: present
        force: true
        name: "backup-{{ volume_id }}-{{ ansible_date_time.iso8601_basic_short }}"
      register: backup_result
    
    - name: Show backup result
      debug:
        var: backup_result.backup
      when: backup_result.backup is defined
      tags: debug
