---
# ============================================
# Cinder Volume Backup - VERSIONE FINALE
# Usa solo moduli Ansible (no shell commands)
# ============================================

- name: Execute OpenStack Cinder Volume Backup
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
    # =============================================
    # 1. VALIDAZIONE INPUT
    # =============================================
    
    - name: Ensure volume_id is provided
      assert:
        that: volume_id is defined and volume_id | length > 0
        fail_msg: "ERROR: volume_id is missing"
        success_msg: "Volume ID received: {{ volume_id }}"
    
    # =============================================
    # 2. IMPOSTA DEFAULT
    # =============================================
    
    - name: Set default retention
      set_fact:
        retention_days: "{{ retention_days | default(15) }}"
    
    - name: Set tenant_name from variable or environment
      set_fact:
        tenant_name: "{{ tenant_name | default(lookup('env', 'OS_PROJECT_NAME') | default('default')) }}"
    
    # =============================================
    # 3. RECUPERA NOME VOLUME DA OPENSTACK
    # =============================================
    
    - name: Get volume info from OpenStack
      openstack.cloud.volume_info:
        name: "{{ volume_id }}"
      register: volume_info
    
    - name: Check if volume exists
      fail:
        msg: "Volume {{ volume_id }} not found"
      when: volume_info.volumes | length == 0
    
    - name: Set volume name
      set_fact:
        volume_name: "{{ volume_info.volumes[0].name }}"
    
    # =============================================
    # 4. GENERA NOME BACKUP
    # Format: anno_mese_giorno_backup_volumename_tenantname
    # =============================================
    
    - name: Clean volume name
      set_fact:
        clean_volume_name: "{{ volume_name | regex_replace('[^a-zA-Z0-9_-]', '_') }}"
    
    - name: Clean tenant name
      set_fact:
        clean_tenant_name: "{{ tenant_name | regex_replace('[^a-zA-Z0-9_-]', '_') }}"
    
    - name: Generate backup name
      set_fact:
        backup_name: "{{ ansible_date_time.year }}_{{ '%02d' | format(ansible_date_time.month | int) }}_{{ '%02d' | format(ansible_date_time.day | int) }}_backup_{{ clean_volume_name }}_{{ clean_tenant_name }}"
    
    - name: Display backup info
      debug:
        msg:
          - "=============================================="
          - "BACKUP VOLUME OPENSTACK"
          - "=============================================="
          - "Volume ID: {{ volume_id }}"
          - "Volume Name: {{ volume_name }}"
          - "Tenant: {{ tenant_name }}"
          - "Backup Name: {{ backup_name }}"
          - "Retention: {{ retention_days }} giorni"
          - "=============================================="
    
    # =============================================
    # 5. CREA BACKUP
    # =============================================
    
    - name: Create OpenStack volume backup
      openstack.cloud.volume_backup:
        volume: "{{ volume_id }}"
        state: present
        force: true
        name: "{{ backup_name }}"
        description: "Backup automatico daily - Retention {{ retention_days }}gg - Tenant: {{ tenant_name }}"
      register: backup_result
    
    - name: Show backup result
      debug:
        msg: 
          - "✓ Backup created successfully!"
          - "Name: {{ backup_result.backup.name }}"
          - "ID: {{ backup_result.backup.id }}"
          - "Status: {{ backup_result.backup.status }}"
      when: backup_result.backup is defined
    
    # =============================================
    # 6. APPLICA RETENTION POLICY (15gg)
    # =============================================
    
    - name: Get all backups for this volume
      openstack.cloud.volume_backup_info:
        volume: "{{ volume_id }}"
      register: all_backups_info
      ignore_errors: true
    
    - name: Set backups list
      set_fact:
        all_backups: "{{ all_backups_info.backups | default([]) }}"
      when: all_backups_info is defined
    
    - name: Calculate retention date
      set_fact:
        retention_date: "{{ '%Y-%m-%d' | strftime((ansible_date_time.epoch | int) - (retention_days | int * 86400)) }}"
    
    - name: Find old backups to delete
      set_fact:
        old_backups: "{{ all_backups | selectattr('created_at', 'defined') | selectattr('created_at', 'lt', retention_date) | list }}"
      when: all_backups | length > 0
    
    - name: Display retention info
      debug:
        msg:
          - "Retention: {{ retention_days }} giorni"
          - "Cutoff date: {{ retention_date }}"
          - "Total backups: {{ all_backups | length }}"
          - "Backups to delete: {{ old_backups | default([]) | length }}"
    
    - name: Delete old backups
      openstack.cloud.volume_backup:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ old_backups }}"
      when:
        - old_backups is defined
        - old_backups | length > 0
      register: delete_results
      ignore_errors: true
    
    - name: Show cleanup result
      debug:
        msg: "✓ Retention applied - Deleted {{ delete_results.results | default([]) | length }} old backup(s)"
      when:
        - old_backups is defined
        - old_backups | length > 0
    
    # =============================================
    # 7. RIEPILOGO FINALE
    # =============================================
    
    - name: Final summary
      debug:
        msg:
          - "=============================================="
          - "BACKUP COMPLETATO"
          - "=============================================="
          - "Backup Name: {{ backup_name }}"
          - "Backup ID: {{ backup_result.backup.id | default('N/A') }}"
          - "Volume: {{ volume_name }} ({{ volume_id }})"
          - "Tenant: {{ tenant_name }}"
          - "Retention: {{ retention_days }} giorni"
          - "Old backups deleted: {{ old_backups | default([]) | length }}"
          - "=============================================="
