---
- name: Delete OpenStack Load Balancer
  hosts: localhost
  gather_facts: no
  
  vars:
    lb_name: "{{ lb_name }}"
    
  tasks:
    - name: Delete Load Balancer
      openstack.cloud.loadbalancer:
        name: "{{ lb_name }}"
        state: absent
        wait: yes
        timeout: 300
      register: lb_result
      
    - name: Show deletion result
      debug:
        msg: "Load Balancer {{ lb_name }} deleted successfully"
      when: lb_result.changed
      
    - name: Load Balancer not found
      debug:
        msg: "Load Balancer {{ lb_name }} not found or already deleted"
      when: not lb_result.changed
