---
- name: List Active Backup Schedules for Volume
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    awx_host: "https://services.xaaslab.it"
    awx_user: "paolo.astorino"
    awx_password: "gaxH=5[]zu22"
    awx_validate_certs: false
  
  tasks:
    # Validazione input
    - name: Validate required variables
      assert:
        that:
          - volume_id is defined and volume_id | length > 0
        fail_msg: "ERROR: Missing volume_id"
        success_msg: "Volume ID received: {{ volume_id }}"
    
    # Recupera info volume
    - name: Get volume info from OpenStack
      openstack.cloud.volume_info:
        details: true
      register: all_volumes
    
    # DEBUG: Mostra tutti i volumi e i loro ID
    - name: Debug - Show all volumes
      debug:
        msg: "Volume: {{ item.name }} - ID: {{ item.id }}"
      loop: "{{ all_volumes.volumes }}"
    
    - name: Debug - Show volume_id we're looking for
      debug:
        msg: "Looking for volume_id: {{ volume_id }}"
    
    # Prova a cercare il volume in modi diversi
    - name: Find volume by ID (exact match)
      set_fact:
        matching_volumes: "{{ all_volumes.volumes | selectattr('id', 'equalto', volume_id) | list }}"
    
    - name: Debug - Matching volumes found
      debug:
        msg: "Found {{ matching_volumes | length }} matching volumes"
    
    # Se non lo trova con equalto, prova con 'in' o 'search'
    - name: Try alternate search if no match
      set_fact:
        matching_volumes: "{{ all_volumes.volumes | selectattr('id', 'search', volume_id) | list }}"
      when: matching_volumes | length == 0
    
    - name: Debug - After alternate search
      debug:
        msg: "After alternate search: Found {{ matching_volumes | length }} matching volumes"
    
    # Se ancora non lo trova, mostra tutti gli attributi del primo volume
    - name: Debug - Show first volume attributes
      debug:
        var: all_volumes.volumes[0]
      when: all_volumes.volumes | length > 0
    
    - name: Set volume data and name
      set_fact:
        volume_data: "{{ matching_volumes[0] }}"
        volume_name: "{{ matching_volumes[0].name }}"
      when: matching_volumes | length > 0
    
    # Recupera tutti gli schedule da AWX
    - name: Get all schedules from AWX
      uri:
        url: "{{ awx_host }}/api/v2/schedules/"
        method: GET
        user: "{{ awx_user }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        validate_certs: "{{ awx_validate_certs }}"
        return_content: yes
      register: awx_schedules
      when: matching_volumes | length > 0
    
    # Filtra schedule per questo volume
    - name: Filter schedules for this volume
      set_fact:
        volume_schedules: "{{ awx_schedules.json.results | selectattr('name', 'search', volume_id) | list }}"
      when: matching_volumes | length > 0
    
    # Mostra risultati
    - name: Display active schedules
      debug:
        msg:
          - "=============================================="
          - "ACTIVE BACKUP SCHEDULES"
          - "=============================================="
          - "Volume: {{ volume_name | default('Unknown') }} ({{ volume_id }})"
          - "Number of active schedules: {{ volume_schedules | length }}"
          - "=============================================="
      when: 
        - matching_volumes | length > 0
        - volume_schedules is defined
        - volume_schedules | length > 0
    
    - name: Display each schedule
      debug:
        msg:
          - "Schedule Name: {{ item.name }}"
          - "Schedule ID: {{ item.id }}"
          - "Next Run: {{ item.next_run | default('N/A') }}"
          - "Enabled: {{ item.enabled }}"
          - "---"
      loop: "{{ volume_schedules }}"
      when: 
        - matching_volumes | length > 0
        - volume_schedules is defined
        - volume_schedules | length > 0
    
    - name: No schedules found
      debug:
        msg: "No active backup schedules found for this volume"
      when: 
        - matching_volumes | length > 0
        - volume_schedules is defined
        - volume_schedules | length == 0
    
    - name: Volume not found
      debug:
        msg: "Volume {{ volume_id }} not found in OpenStack. Please check the volume ID."
      when: matching_volumes | length == 0
