---
- name: Create L4 TCP Load Balancer (Dynamic)
  hosts: localhost
  gather_facts: no
  collections:
    - openstack.cloud
  
  vars:
    # ❌ RIMUOVI cloud_name
    # cloud_name: openstack
    
    protocol: "{{ protocol | default('TCP') }}"
    lb_algorithm_default: "{{ lb_algorithm | default('ROUND_ROBIN') }}"
    listener_name: "{{ lb_name }}-listener"
    pool_name: "{{ lb_name }}-pool"
  
  tasks:
    - name: Validate required variables
      assert:
        that:
          - lb_name is defined
          - lb_name | length > 0
          - lb_vip_subnet is defined
          - listener_port is defined
          - listener_port | int > 0
          - listener_port | int < 65536
          - lb_members is defined
          - lb_members | length > 0
        fail_msg: |
          ❌ Variabili richieste mancanti o non valide!
    
    - name: Log configuration
      debug:
        msg: |
          📋 Configurazione Load Balancer:
          Nome: {{ lb_name }}
          Subnet VIP: {{ lb_vip_subnet }}
          Porta: {{ listener_port }}
          Membri: {{ lb_members | length }}
    
    - name: Ensure no existing load balancer (cleanup)
      openstack.cloud.loadbalancer:
        # ❌ NON specificare cloud: "{{ cloud_name }}"
        name: "{{ lb_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Create Load Balancer
      openstack.cloud.loadbalancer:
        # ❌ NON specificare cloud
        name: "{{ lb_name }}"
        vip_subnet: "{{ lb_vip_subnet }}"
        state: present
        wait: yes
        timeout: 800
      register: lb_created
    
    - name: Create TCP Listener
      openstack.cloud.lb_listener:
        # ❌ NON specificare cloud
        load_balancer: "{{ lb_name }}"
        name: "{{ listener_name }}"
        protocol: "{{ protocol | upper }}"
        protocol_port: "{{ listener_port | int }}"
        state: present
        wait: yes
        timeout: 120
    
    - name: Create TCP Pool
      openstack.cloud.lb_pool:
        # ❌ NON specificare cloud
        listener: "{{ listener_name }}"
        name: "{{ pool_name }}"
        protocol: "{{ protocol | upper }}"
        lb_algorithm: "{{ lb_algorithm_default }}"
        state: present
        wait: yes
        timeout: 120
    
    - name: Add members to pool
      openstack.cloud.lb_member:
        # ❌ NON specificare cloud
        pool: "{{ pool_name }}"
        name: "member-{{ item.address }}-{{ item.protocol_port }}"
        address: "{{ item.address }}"
        protocol_port: "{{ item.protocol_port | int }}"
        subnet_id: "{{ lb_vip_subnet }}"
        state: present
      loop: "{{ lb_members }}"
    
    - name: Get Load Balancer info (con CLI)
      command: >
        openstack loadbalancer show {{ lb_name }} -f json
      register: lb_info_json
      changed_when: false
      # Per la CLI serve specificare --os-cloud o usare env vars
    
    - set_fact:
        lb_info: "{{ lb_info_json.stdout | from_json }}"
    
    - name: Show final summary
      debug:
        msg: |
          ✅✅✅ Load Balancer COMPLETATO ✅✅✅
          📛 Nome: {{ lb_name }}
          🔒 VIP: {{ lb_info.vip_address }}
          🚪 Porta: {{ listener_port }}
          🖥️  Backend: {{ lb_members | map(attribute='address') | list }}
