---
# ============================================
# Playbook AWX: Manage Cinder Volume Backup Schedule (MULTI-TENANT)
# Supporta: enable, disable, activate, deactivate
# ============================================

- name: Manage Cinder Volume Backup Schedule
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    awx_host: "https://services.linuxwall.it"
    awx_user: "paolo.astorino"
    awx_password: "gaxH=5[]zu22"
    awx_validate_certs: false
    retention_days: 15
  
  tasks:
    # =============================================
    # 1. VALIDAZIONE INPUT
    # =============================================
    
    - name: Validate required variables
      assert:
        that:
          - volume_id is defined and volume_id | length > 0
          - backup_action is defined and backup_action | length > 0
          - backup_action in ['enable', 'disable', 'activate', 'deactivate']
          - openstack_auth_url is defined
          - openstack_username is defined
          - openstack_password is defined
          - (openstack_project_id is defined) or (openstack_project_name is defined)
        fail_msg: "ERROR: Missing or invalid variables"
        success_msg: "✓ Variables OK - volume_id: {{ volume_id }}, action: {{ backup_action }}"
    
    - name: Validate schedule_id for activate/deactivate actions
      assert:
        that:
          - schedule_id is defined and schedule_id | length > 0
        fail_msg: "ERROR: schedule_id is required for activate/deactivate actions"
      when: backup_action in ['activate', 'deactivate']
    
    - name: Validate backup_name for enable action
      assert:
        that:
          - backup_name is defined and backup_name | length > 0
        fail_msg: "ERROR: backup_name is required for enable action"
      when: backup_action == 'enable'
    
    # =============================================
    # 2. AUTHENTICATE OPENSTACK KEYSTONE (MULTI-TENANT)
    # =============================================
    
    - name: Determine authentication method
      set_fact:
        use_project_id: "{{ openstack_project_id is defined and openstack_project_id != '' }}"

    - name: Log authentication
      debug:
        msg: "🔐 Autenticazione OpenStack: {{ 'Project ID (UUID)' if use_project_id else 'Project Name' }} = {{ openstack_project_id if use_project_id else openstack_project_name }}"

    - name: Authenticate with project ID
      uri:
        url: "{{ openstack_auth_url }}/v3/auth/tokens"
        method: POST
        body:
          auth:
            identity:
              methods: [password]
              password:
                user:
                  name: "{{ openstack_username }}"
                  domain:
                    name: "{{ openstack_domain_name | default('Default') }}"
                  password: "{{ openstack_password }}"
            scope:
              project:
                id: "{{ openstack_project_id }}"
        body_format: json
        status_code: 201
        return_content: yes
        validate_certs: no
      register: auth_with_id
      when: use_project_id | bool

    - name: Authenticate with project name
      uri:
        url: "{{ openstack_auth_url }}/v3/auth/tokens"
        method: POST
        body:
          auth:
            identity:
              methods: [password]
              password:
                user:
                  name: "{{ openstack_username }}"
                  domain:
                    name: "{{ openstack_domain_name | default('Default') }}"
                  password: "{{ openstack_password }}"
            scope:
              project:
                name: "{{ openstack_project_name }}"
                domain:
                  name: "{{ openstack_domain_name | default('Default') }}"
        body_format: json
        status_code: 201
        return_content: yes
        validate_certs: no
      register: auth_with_name
      when: not (use_project_id | bool)

    - name: Set unified auth response
      set_fact:
        auth_response: "{{ auth_with_id if (auth_with_id is defined and not auth_with_id.skipped | default(false)) else auth_with_name }}"

    - name: Extract auth token
      set_fact:
        os_auth_token: "{{ auth_response.x_subject_token }}"

    - name: Set final tenant name
      set_fact:
        tenant_name: "{{ openstack_project_name | default(auth_response.json.token.project.name) }}"

    - name: Log successful authentication
      debug:
        msg: "✅ Autenticato su OpenStack | Tenant: {{ tenant_name }}"
    
    # =============================================
    # 3. VERIFICA ESISTENZA VOLUME (con autenticazione)
    # =============================================
    
    - name: Check if volume exists in OpenStack
      block:
        - name: Get volume info with explicit auth
          openstack.cloud.volume_info:
            auth:
              auth_url: "{{ openstack_auth_url }}"
              username: "{{ openstack_username }}"
              password: "{{ openstack_password }}"
              project_id: "{{ openstack_project_id | default(omit) }}"
              project_name: "{{ openstack_project_name | default(omit) }}"
              domain_name: "{{ openstack_domain_name | default('Default') }}"
            details: true
          register: all_volumes
        
        - name: Find volume by ID
          set_fact:
            volume_data: "{{ all_volumes.volumes | selectattr('id', 'equalto', volume_id) | first | default(None) }}"
        
        - name: Check if volume was found
          set_fact:
            volume_exists: "{{ volume_data is not none }}"
        
        - name: Set volume name from OpenStack
          set_fact:
            volume_name: "{{ volume_data.name }}"
          when: volume_exists
        
        - name: Display success - volume found
          debug:
            msg: "✓ Volume trovato in OpenStack: {{ volume_name }} ({{ volume_id }})"
          when: volume_exists
        
        - name: Fail if volume doesn't exist
          fail:
            msg: "❌ Volume {{ volume_id }} non trovato nel tenant {{ tenant_name }}"
