---
- name: Schedule Cinder Volume Backup Jobs on AWX
  hosts: localhost
  connection: local  # ← FONDAMENTALE
  gather_facts: false

  vars:
    awx_host: "https://abcd-123-45-67-89.ngrok-free.app"  # ← il tuo ngrok URL
    awx_token: "4yMLwb0CljM93Qf4KqUroMRITgj3eSZg"                     # ← token da AWX
    awx_validate_certs: false

  tasks:
    - name: Create AWX job template for volume backup
      awx.awx.job_template:
        name: "Cinder Volume Backup"
        project: "project-test"
        playbook: "playbook-volume-backup.yml"
        inventory: "inventory-backup-test"
        state: present
        controller_host: "{{ awx_host }}"
        controller_oauthtoken: "{{ awx_token }}"
        validate_certs: "{{ awx_validate_certs }}"

    - name: Create AWX schedule for daily backup
      awx.awx.schedule:
        name: "Daily Cinder Backup"
        unified_job_template: "Cinder Volume Backup"
        rrule: "DTSTART;TZID=UTC:20251009T000000 RRULE:FREQ=DAILY;INTERVAL=1"
        state: present
        controller_host: "{{ awx_host }}"
        controller_oauthtoken: "{{ awx_token }}"
        validate_certs: "{{ awx_validate_certs }}"

    - name: Create AWX schedule for weekly backup
      awx.awx.schedule:
        name: "Weekly Cinder Backup"
        unified_job_template: "Cinder Volume Backup"
        rrule: "DTSTART;TZID=UTC:20251009T000000 RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=MO"
        state: present
        controller_host: "{{ awx_host }}"
        controller_oauthtoken: "{{ awx_token }}"
        validate_certs: "{{ awx_validate_certs }}"
